TO DO File 

Exercise:

In [ ]:
def convert(unit, value):
    if unit == 'm':
        return value * 3.28084
    elif unit == 'n':
        return value / 3.28084
    elif unit == 'o':
        return value * 2.20462
    elif unit == 'p':
        return value / 2.20462
    elif unit == 'q':
        return value * 0.264172
    elif unit == 'r':
        return value / 0.264172
    else: 
        return None

print("M: Meters to Ft\nN: Ft to Meters\nO: Kilograms to pounds\nP: Pounds to kilograms\nQ: liters to Gallons\nR: Gallons to Liters")

choose = input("Enter a alphabets(M - R): ").lower()

value = float(input("Enter value: "))
Output = convert(choose, value)
print(f"Final Converted Value: {Output:.4f}")

M: Meters to Ft
N: Ft to Meters
O: Kilograms to pounds
P: Pounds to kilograms
Q: liters to Gallons
R: Gallons to Liters
Converted Value: 39.3701


In [16]:
#Task 2

def calc_sum(values):
    return sum(values)
def calc_avg(values):
    return sum(values) / len(values)
def calc_max(values):
    return max(values)
def calc_min(values):
    return min(values)

def main():
    print("Select an Operation: ")
    print("1. Sum") 
    print("2. Average") 
    print("3. Maximum") 
    print("4. Minimum") 

    try:
        operation = int(input("which operation do you want to do: "))

        if operation not in [1,2,3,4]:
            print("Invalid selection.")
            return
        
        numbers_input = input("Enter list of number: ")
        numbers = list(map(float, numbers_input.split()))
        if operation == 1:
            print("Sum:",calc_sum(numbers))
        elif operation == 2:
            print("Average:", calc_avg(numbers))
        elif operation == 3:
            print("Maximum:", calc_max(numbers))
        elif operation == 4:
            print("Minimum:", calc_min(numbers))

    except ValueError:
        print("Invalid Input")

if __name__ == "__main__":
    main()



Select an Operation: 
1. Sum
2. Average
3. Maximum
4. Minimum
Sum: 12.0


In [17]:
def extract_alternate(elements):
    return elements[::2]

def get_range(elements, start_idx, end_idx):
    return elements[start_idx:end_idx+1]

def reverse_elements(elements):
    return elements[::-1]

def trim_edges(elements):
    return elements[1:-1]

def get_first_k(elements, k):
    return elements[:k]

def get_last_k(elements, k):
    return elements[-k:]

def reverse_skip_alternate(elements):
    return elements[-2::-2]

data = [1, 2, 3, 4, 5, 6, 7, 8, 9]
print(extract_alternate(data))
print(get_range(data, 2, 5))
print(reverse_elements(data))
print(trim_edges(data))
print(get_first_k(data, 4))
print(get_last_k(data, 3))
print(reverse_skip_alternate(data))


[1, 3, 5, 7, 9]
[3, 4, 5, 6]
[9, 8, 7, 6, 5, 4, 3, 2, 1]
[2, 3, 4, 5, 6, 7, 8]
[1, 2, 3, 4]
[7, 8, 9]
[8, 6, 4, 2]


In [11]:
def flatten_list(nested_list):
    flat_list = []
    for element in nested_list:
        if isinstance(element, list):
            flat_list.extend(flatten_list(element))
        else:
            flat_list.append(element)
    return flat_list

def access_element(nested_list, path):
    for idx in path:
        nested_list = nested_list[idx]
    return nested_list

def sum_of_elements(nested_list):
    total = 0
    for element in nested_list:
        if isinstance(element, list):
            total += sum_of_elements(element)
        else:
            total += element
    return total

def remove_value(nested_list, value):
    for i in range(len(nested_list)):
        if isinstance(nested_list[i], list):
            nested_list[i] = remove_value(nested_list[i], value)
        else:
            if nested_list[i] == value:
                nested_list[i] = None
    return [item for item in nested_list if item is not None]
def find_max_value(nested_list):
    max_value = float('-inf')
    for element in nested_list:
        if isinstance(element, list):
            max_value = max(max_value, find_max_value(element))
        else:
            max_value = max(max_value, element)
    return max_value

def count_value_occurrences(nested_list, value):
    count = 0
    for element in nested_list:
        if isinstance(element, list):
            count += count_value_occurrences(element, value)
        else:
            if element == value:
                count += 1
    return count

def deep_flatten_list(nested_list):
    flat_list = []
    for element in nested_list:
        if isinstance(element, list):
            flat_list.extend(deep_flatten_list(element))
        else:
            flat_list.append(element)
    return flat_list

def average_of_elements(nested_list):
    def calculate_sum_and_count(nested_list):
        total_sum = 0
        count = 0
        for element in nested_list:
            if isinstance(element, list):
                nested_sum, nested_count = calculate_sum_and_count(element)
                total_sum += nested_sum
                count += nested_count
            else:
                total_sum += element
                count += 1
        return total_sum, count

    total_sum, count = calculate_sum_and_count(nested_list)
    
    if count == 0:
        return 0
    else:
        return total_sum / count
    

In [19]:
nested_lst = [[1, 2], [3, [4, 5]], 6]
print(flatten_list(nested_lst)) 
print(access_element(nested_lst, [1, 1]))
print(sum_of_elements(nested_lst)) 
nested_lst2 = [[1, 2], [3, 2], [4, 5]]
print(remove_value(nested_lst2, 2))
print(find_max_value(nested_lst))
print("Occurrences of 2:", count_value_occurrences(nested_lst2, 2)) 
nested_lst3 = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
print(deep_flatten_list(nested_lst3)) 
nested_lst4 = [[1, 2], [3, 4], [5, 6]]
print(average_of_elements(nested_lst4))

[1, 2, 3, 4, 5, 6]
[4, 5]
21
[[1], [3], [4, 5]]
6
Occurrences of 2: 0
[1, 2, 3, 4, 5, 6, 7, 8]
3.5


Numpy

In [3]:
import numpy as np
empty_array = np.empty((2, 2))
print(empty_array)

ones_array = np.ones((4, 2))
print("\n",ones_array)

shape = (3, 3)
fill_value = 7
filled_array = np.full(shape, fill_value)
print("\n",filled_array)

given_array = np.array([[1, 2], [3, 4]])
zeros_like_array = np.zeros_like(given_array)
print("\n",zeros_like_array)

ones_like_array = np.ones_like(given_array)
print("\n",ones_like_array)

new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)
print("\n",numpy_array)

[[5.50929512e-279 5.98123966e-154]
 [1.28625721e+248 1.66041814e+243]]

 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

 [[7 7 7]
 [7 7 7]
 [7 7 7]]

 [[0 0]
 [0 0]]

 [[1 1]
 [1 1]]

 [1 2 3 4]


In [10]:
ar1 = np.arange(5, 50)
print("\n", ar1)

ar2 = np.arange(9).reshape(3, 3)
print("\n", ar2)

ar3 = np.eye(3)
print("\n", ar3)


ar4 = np.random.random(30)
mean_arr4 = ar4.mean()
print("\n", ar4)
print("\nMean", mean_arr4)

ar5 = np.random.random((10, 10))
min_value = ar5.min()
max_value = ar5.max()
print("\n", ar5)
print("\nMin", min_value)
print("\nMax", max_value)

ar6 = np.zeros(10)
ar6[4] = 1 
print("\n", ar6)

ar7 = np.array([3, 2, 1, 0, 4, 0])
reversed_ar7 = ar7[::-1]
print("\n", reversed_ar7)

ar8 = np.ones((7, 7))
ar8[1:-1, 1:-1] = 0
print("\n", ar8)

ar9 = np.zeros((9, 9), dtype=int)
ar9[1::2, ::2] = 1
ar9[::2, 1::2] = 1
print("\n", ar9)




 [ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28
 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

 [[0 1 2]
 [3 4 5]
 [6 7 8]]

 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

 [0.0678097  0.95818797 0.02788941 0.66950856 0.91669029 0.13669483
 0.52233086 0.02217617 0.36900044 0.37873551 0.18267223 0.37314717
 0.00393407 0.43962169 0.99017653 0.17700808 0.9088718  0.0232747
 0.46715565 0.80114245 0.89711989 0.69248759 0.93382732 0.67698816
 0.91150774 0.68425628 0.14597215 0.0124199  0.69987005 0.91944609]

Mean 0.5003307755549933

 [[0.8814204  0.32488665 0.94155756 0.38350275 0.19799712 0.63380015
  0.44180162 0.97806005 0.05272157 0.06053974]
 [0.70912401 0.01594666 0.64869725 0.34083662 0.02807876 0.46951632
  0.33363656 0.29803432 0.43121166 0.44182422]
 [0.10397475 0.63266639 0.41264874 0.59448881 0.74236828 0.84604742
  0.39991908 0.81974014 0.16184908 0.72728395]
 [0.89750463 0.73336289 0.36721013 0.56802669 0.45796442 0.60491563
  0.52768396 0

In [18]:
a = np.array([[3, 4], [5, 5]])
b = np.array([[2, 6], [2, 4]])
c = np.array([8, 12])
d = np.array([10, 12])

Sum = a + b
print("sum of a and b:\n", Sum)

diff = a - b
print("difference of a and b:\n", diff)

product_a = a * 4
product_b = b * 5
print("Multiplying a by 4:\n", product_a)
print("Multiplying b by 5:\n", product_b)

dot_cd = np.dot(c, d)
dot_ac = np.dot(a, c)
dot_ab = np.dot(a, b)

print("Dot product of c and d:", dot_cd)
print("Dot product of a and c:\n", dot_ac)
print("Dot product of a and b:\n", dot_ab)

concatenate_ab_row = np.concatenate((a, b), axis=0)
concatenate_cd_col = np.concatenate((c.reshape(-1, 1), d.reshape(-1, 1)), axis=1)

print("Concatenating a and b along row:\n", concatenate_ab_row)
print("Concatenating c and d along column:\n", concatenate_cd_col)

sum of a and b:
 [[ 5 10]
 [ 7  9]]
difference of a and b:
 [[ 1 -2]
 [ 3  1]]
Multiplying a by 4:
 [[12 16]
 [20 20]]
Multiplying b by 5:
 [[10 30]
 [10 20]]
Dot product of c and d: 224
Dot product of a and c:
 [ 72 100]
Dot product of a and b:
 [[14 34]
 [20 50]]
Concatenating a and b along row:
 [[3 4]
 [5 5]
 [2 6]
 [2 4]]
Concatenating c and d along column:
 [[ 8 10]
 [12 12]]


In [22]:
import numpy as np


X = np.array([[3,4], [7,8]])
Y = np.array([[5,3], [2,1]])

#calculating of inverse of x
X_inverse = np.linalg.inv(X)

identity_matrix = np.dot(X, X_inverse)
print("X * X_inverse:\n ", identity_matrix)

#Matrix Multiplication
XY = np.dot(X, Y)
YX = np.dot(Y, X)
print("XY:\n ", XY)
print("YX:\n", YX)

#Transpose verification
XY_Tp = XY.T
YTp_XTp = np.dot(Y.T, X.T)

print("Transpose of XY:\n", XY_Tp)
print("Y^T * X^T:\n", YTp_XTp)

Z = np.array([[2, -3, 1], [1, -1, 2], [3,1, -1]])
A = np.array([[-1], [-3], [9]])

Z_inv = np.linalg.inv(Z)
soln1 = np.dot(Z_inv, A)
print("\n Output using inverse:\n", soln1)

soln2 = np.linalg.solve(Z, A)
print("\n Output using np.linalg.solve:\n", soln2)



X * X_inverse:
  [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
XY:
  [[23 13]
 [51 29]]
YX:
 [[36 44]
 [13 16]]
Transpose of XY:
 [[23 51]
 [13 29]]
Y^T * X^T:
 [[23 51]
 [13 29]]

 Output using inverse:
 [[ 2.]
 [ 1.]
 [-2.]]

 Output using np.linalg.solve:
 [[ 2.]
 [ 1.]
 [-2.]]
